name: lint-pr

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited]

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: yogevbd/pr-lint-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
