name: Lint PR

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited]

jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/pr-lint-action@prBodyParser
      env:
        VALID_LABELS: bug,enhancement,feature
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}